setwd("C:/Users/Ann Umadhay/Documents/UP ANN S14/4th year 2nd sem/Stat197/3rd activity/Ann Umadhay - CourseProject3-data")
outcome <- read.csv("outcome-of-care-measures.csv", colClasses="character")
head(outcome)
outcome[,11] <- as.numeric(outcome[,11])
hist(outcome[,11], xlab = "30-day Death Rate", main = "Heart Attack 30-day Death Rate")
